pyseer --lmm --phenotypes pyseerData/y_1.pheno --vcf pyseerData/SNP_1.vcf --similarity pyseerData/MDS_K1.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result1.txt
pyseer --lmm --phenotypes pyseerData/y_2.pheno --vcf pyseerData/SNP_2.vcf --similarity pyseerData/MDS_K2.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result2.txt
pyseer --lmm --phenotypes pyseerData/y_3.pheno --vcf pyseerData/SNP_3.vcf --similarity pyseerData/MDS_K3.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result3.txt
pyseer --lmm --phenotypes pyseerData/y_4.pheno --vcf pyseerData/SNP_4.vcf --similarity pyseerData/MDS_K4.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result4.txt
pyseer --lmm --phenotypes pyseerData/y_5.pheno --vcf pyseerData/SNP_5.vcf --similarity pyseerData/MDS_K5.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result5.txt
pyseer --lmm --phenotypes pyseerData/y_6.pheno --vcf pyseerData/SNP_6.vcf --similarity pyseerData/MDS_K6.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result6.txt
pyseer --lmm --phenotypes pyseerData/y_7.pheno --vcf pyseerData/SNP_7.vcf --similarity pyseerData/MDS_K7.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result7.txt
pyseer --lmm --phenotypes pyseerData/y_8.pheno --vcf pyseerData/SNP_8.vcf --similarity pyseerData/MDS_K8.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result8.txt
pyseer --lmm --phenotypes pyseerData/y_9.pheno --vcf pyseerData/SNP_9.vcf --similarity pyseerData/MDS_K9.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result9.txt
pyseer --lmm --phenotypes pyseerData/y_10.pheno --vcf pyseerData/SNP_10.vcf --similarity pyseerData/MDS_K10.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result10.txt
pyseer --lmm --phenotypes pyseerData/y_11.pheno --vcf pyseerData/SNP_11.vcf --similarity pyseerData/MDS_K11.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result11.txt
pyseer --lmm --phenotypes pyseerData/y_12.pheno --vcf pyseerData/SNP_12.vcf --similarity pyseerData/MDS_K12.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result12.txt
pyseer --lmm --phenotypes pyseerData/y_13.pheno --vcf pyseerData/SNP_13.vcf --similarity pyseerData/MDS_K13.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result13.txt
pyseer --lmm --phenotypes pyseerData/y_14.pheno --vcf pyseerData/SNP_14.vcf --similarity pyseerData/MDS_K14.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result14.txt
pyseer --lmm --phenotypes pyseerData/y_15.pheno --vcf pyseerData/SNP_15.vcf --similarity pyseerData/MDS_K15.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result15.txt
pyseer --lmm --phenotypes pyseerData/y_16.pheno --vcf pyseerData/SNP_16.vcf --similarity pyseerData/MDS_K16.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result16.txt
pyseer --lmm --phenotypes pyseerData/y_17.pheno --vcf pyseerData/SNP_17.vcf --similarity pyseerData/MDS_K17.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result17.txt
pyseer --lmm --phenotypes pyseerData/y_18.pheno --vcf pyseerData/SNP_18.vcf --similarity pyseerData/MDS_K18.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result18.txt
pyseer --lmm --phenotypes pyseerData/y_19.pheno --vcf pyseerData/SNP_19.vcf --similarity pyseerData/MDS_K19.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result19.txt
pyseer --lmm --phenotypes pyseerData/y_20.pheno --vcf pyseerData/SNP_20.vcf --similarity pyseerData/MDS_K20.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result20.txt
pyseer --lmm --phenotypes pyseerData/y_21.pheno --vcf pyseerData/SNP_21.vcf --similarity pyseerData/MDS_K21.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result21.txt
pyseer --lmm --phenotypes pyseerData/y_22.pheno --vcf pyseerData/SNP_22.vcf --similarity pyseerData/MDS_K22.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result22.txt
pyseer --lmm --phenotypes pyseerData/y_23.pheno --vcf pyseerData/SNP_23.vcf --similarity pyseerData/MDS_K23.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result23.txt
pyseer --lmm --phenotypes pyseerData/y_24.pheno --vcf pyseerData/SNP_24.vcf --similarity pyseerData/MDS_K24.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result24.txt
pyseer --lmm --phenotypes pyseerData/y_25.pheno --vcf pyseerData/SNP_25.vcf --similarity pyseerData/MDS_K25.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result25.txt
pyseer --lmm --phenotypes pyseerData/y_26.pheno --vcf pyseerData/SNP_26.vcf --similarity pyseerData/MDS_K26.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result26.txt
pyseer --lmm --phenotypes pyseerData/y_27.pheno --vcf pyseerData/SNP_27.vcf --similarity pyseerData/MDS_K27.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result27.txt
pyseer --lmm --phenotypes pyseerData/y_28.pheno --vcf pyseerData/SNP_28.vcf --similarity pyseerData/MDS_K28.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result28.txt
pyseer --lmm --phenotypes pyseerData/y_29.pheno --vcf pyseerData/SNP_29.vcf --similarity pyseerData/MDS_K29.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result29.txt
pyseer --lmm --phenotypes pyseerData/y_30.pheno --vcf pyseerData/SNP_30.vcf --similarity pyseerData/MDS_K30.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result30.txt
pyseer --lmm --phenotypes pyseerData/y_31.pheno --vcf pyseerData/SNP_31.vcf --similarity pyseerData/MDS_K31.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result31.txt
pyseer --lmm --phenotypes pyseerData/y_32.pheno --vcf pyseerData/SNP_32.vcf --similarity pyseerData/MDS_K32.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result32.txt
pyseer --lmm --phenotypes pyseerData/y_33.pheno --vcf pyseerData/SNP_33.vcf --similarity pyseerData/MDS_K33.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result33.txt
pyseer --lmm --phenotypes pyseerData/y_34.pheno --vcf pyseerData/SNP_34.vcf --similarity pyseerData/MDS_K34.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result34.txt
pyseer --lmm --phenotypes pyseerData/y_35.pheno --vcf pyseerData/SNP_35.vcf --similarity pyseerData/MDS_K35.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result35.txt
pyseer --lmm --phenotypes pyseerData/y_36.pheno --vcf pyseerData/SNP_36.vcf --similarity pyseerData/MDS_K36.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result36.txt
pyseer --lmm --phenotypes pyseerData/y_37.pheno --vcf pyseerData/SNP_37.vcf --similarity pyseerData/MDS_K37.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result37.txt
pyseer --lmm --phenotypes pyseerData/y_38.pheno --vcf pyseerData/SNP_38.vcf --similarity pyseerData/MDS_K38.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result38.txt
pyseer --lmm --phenotypes pyseerData/y_39.pheno --vcf pyseerData/SNP_39.vcf --similarity pyseerData/MDS_K39.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result39.txt
pyseer --lmm --phenotypes pyseerData/y_40.pheno --vcf pyseerData/SNP_40.vcf --similarity pyseerData/MDS_K40.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result40.txt
pyseer --lmm --phenotypes pyseerData/y_41.pheno --vcf pyseerData/SNP_41.vcf --similarity pyseerData/MDS_K41.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result41.txt
pyseer --lmm --phenotypes pyseerData/y_42.pheno --vcf pyseerData/SNP_42.vcf --similarity pyseerData/MDS_K42.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result42.txt
pyseer --lmm --phenotypes pyseerData/y_43.pheno --vcf pyseerData/SNP_43.vcf --similarity pyseerData/MDS_K43.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result43.txt
pyseer --lmm --phenotypes pyseerData/y_44.pheno --vcf pyseerData/SNP_44.vcf --similarity pyseerData/MDS_K44.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result44.txt
pyseer --lmm --phenotypes pyseerData/y_45.pheno --vcf pyseerData/SNP_45.vcf --similarity pyseerData/MDS_K45.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result45.txt
pyseer --lmm --phenotypes pyseerData/y_46.pheno --vcf pyseerData/SNP_46.vcf --similarity pyseerData/MDS_K46.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result46.txt
pyseer --lmm --phenotypes pyseerData/y_47.pheno --vcf pyseerData/SNP_47.vcf --similarity pyseerData/MDS_K47.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result47.txt
pyseer --lmm --phenotypes pyseerData/y_48.pheno --vcf pyseerData/SNP_48.vcf --similarity pyseerData/MDS_K48.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result48.txt
pyseer --lmm --phenotypes pyseerData/y_49.pheno --vcf pyseerData/SNP_49.vcf --similarity pyseerData/MDS_K49.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result49.txt
pyseer --lmm --phenotypes pyseerData/y_50.pheno --vcf pyseerData/SNP_50.vcf --similarity pyseerData/MDS_K50.tsv --min-af 0.00 --max-af 1.00 > pyseerData/result50.txt
