sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo1.newick > pyseerData/MDS_K1.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo2.newick > pyseerData/MDS_K2.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo3.newick > pyseerData/MDS_K3.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo4.newick > pyseerData/MDS_K4.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo5.newick > pyseerData/MDS_K5.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo6.newick > pyseerData/MDS_K6.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo7.newick > pyseerData/MDS_K7.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo8.newick > pyseerData/MDS_K8.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo9.newick > pyseerData/MDS_K9.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo10.newick > pyseerData/MDS_K10.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo11.newick > pyseerData/MDS_K11.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo12.newick > pyseerData/MDS_K12.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo13.newick > pyseerData/MDS_K13.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo14.newick > pyseerData/MDS_K14.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo15.newick > pyseerData/MDS_K15.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo16.newick > pyseerData/MDS_K16.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo17.newick > pyseerData/MDS_K17.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo18.newick > pyseerData/MDS_K18.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo19.newick > pyseerData/MDS_K19.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo20.newick > pyseerData/MDS_K20.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo21.newick > pyseerData/MDS_K21.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo22.newick > pyseerData/MDS_K22.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo23.newick > pyseerData/MDS_K23.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo24.newick > pyseerData/MDS_K24.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo25.newick > pyseerData/MDS_K25.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo26.newick > pyseerData/MDS_K26.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo27.newick > pyseerData/MDS_K27.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo28.newick > pyseerData/MDS_K28.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo29.newick > pyseerData/MDS_K29.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo30.newick > pyseerData/MDS_K30.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo31.newick > pyseerData/MDS_K31.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo32.newick > pyseerData/MDS_K32.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo33.newick > pyseerData/MDS_K33.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo34.newick > pyseerData/MDS_K34.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo35.newick > pyseerData/MDS_K35.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo36.newick > pyseerData/MDS_K36.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo37.newick > pyseerData/MDS_K37.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo38.newick > pyseerData/MDS_K38.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo39.newick > pyseerData/MDS_K39.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo40.newick > pyseerData/MDS_K40.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo41.newick > pyseerData/MDS_K41.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo42.newick > pyseerData/MDS_K42.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo43.newick > pyseerData/MDS_K43.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo44.newick > pyseerData/MDS_K44.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo45.newick > pyseerData/MDS_K45.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo46.newick > pyseerData/MDS_K46.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo47.newick > pyseerData/MDS_K47.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo48.newick > pyseerData/MDS_K48.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo49.newick > pyseerData/MDS_K49.tsv
sudo python scripts/phylogeny_distance.py --lmm pyseerData/phylo50.newick > pyseerData/MDS_K50.tsv
